### ISSUE TITLE
Create a template node

### ISSUE THREAD

**Issue by katyhuff** [necx-org/nodes#4]
Create a base case node that can act as a template for future node contributions.

- Required: 
  - Title
  - uuid
  - Prerequisites (dependencies)
  - Learning objective(s)
  - Explanation Text / Lecture Note / Content
  - Assessment(s)
- Recommended:
  - Text, equations
  - Example code
  - References
  - External readings
  - Instructor guidance
  - Graphics
  - Videos
  - Audio files
  - Worked Examples
  - List ABET a-k objectives supported
  - Active Learning activities
  - Demonstration
  - Code completion exercises
  - Think pair share questions
  - citations/reference
  - Assessment(s)
  - Homework problems
  - Exam problems 
  - Quiz questions
  - Other learning outcomes

**Comment by robertsj** [comment]
I'll take a stab at this.

**Comment by katyhuff** [comment]
This was closed by #23
