### ISSUE TITLE
Set up Jekyll build

### ISSUE THREAD

**Issue by katyhuff** [necx-org/nodes#5]
See also #3 . This can be closed when the nodes render online. This can be in conjunction with, or not in conjunction with, the necx.github.io site.

**Comment by gonuke** [comment]
We should clarify the purpose of this Jekyll build is.  For example, is it likely that anyone will use the Jekyll build directly in a learning environment (I assume not).

I propose that the Jekyll build's audience is an instructor who wants to know what is in a node and assess its value for their purposes.  It could also be the place that we land from meta-tools that help instructors browse the exchange.

**Comment by katyhuff** [comment]
Closed.
