### ISSUE TITLE
Prereqs

### ISSUE THREAD

**Issue by TheDoctorRAB** [necx-org/nodes#55]
Can a node have no prereqs? I'm concerned that they might get too general; e.g., just putting "chemistry".

**Comment by gonuke** [comment]
My own vote is that every node must have at least one pre-req.  How specific they are will be addressed to some degree in review.

**Comment by TheDoctorRAB** [comment]
I guess my problem is that my nodes are basically one removed from the boundary so I'm just having a hard time avoiding being too general; e.g., 'chemistry'.

**Comment by katyhuff** [comment]
Solved with 0a8df16  just now
