### ISSUE TITLE
New Node Script

### ISSUE THREAD

**Issue by katyhuff** [necx-org/nodes#58]
This issue can be closed when the following capability exists:

A script can be run (e.g. `new-node <uid>`) which creates a new node directory structure ready for editing.

**Comment by davis68** [comment]
`new-node` script development:
- fix template node to minimum viable node (MVN)
    - move example exercises to new examples/ directory
    - retain one exercise in MVN
- add jinja fill-in for UID
- write script to copy and update based on template MVN

**Comment by davis68** [comment]
What I'm doing for the first step (in branch `davis68-new-node`):
- copying `template-node` to `template-node-full` as a stub for a "maximal" node
- renaming `special-relativity-exercise.yml` to `basic-exercise.yml` in `template-node`

**Comment by davis68** [comment]
The script now exists in `bin/new-node`.  The directories may need to be updated based on the outcome of the submodule/node location discussion.

**Comment by katyhuff** [comment]
Closed with push.
